# Generated by Django 6.0.5 on 2026-05-07 08:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('data_creation', models.DateTimeField(auto_now_add=True)),
                ('membres', models.ManyToManyField(blank=True, related_name='groups', to='users.user')),
            ],
            options={
                'db_table': 'groups',
                'ordering': ['-data_creation'],
            },
        ),
    ]
