# Generated by Django 6.0.5 on 2026-05-07 08:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clerk_id', models.CharField(max_length=255, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin_global', 'Admin Global'), ('admin_metier', 'Admin Métier'), ('admin_externe', 'Admin Externe'), ('user_interne', 'Utilisateur Interne'), ('user_externe', 'Utilisateur Externe')], default='user_externe', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('free_access', models.BooleanField(default=False)),
                ('organisation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
